### ISSUE TITLE
[BUG] Cannot add video from url

### ISSUE THREAD

**Issue by turtton** [turtton/YtAlarm#196]
**Describe the bug**
バグの内容の簡素な説明

SSIA. I tried yt and soundcloud but both failed.

**To Reproduce**
Steps to reproduce the behavior(再現手順):
1. Go to Videolist
2. Click plus button
3. Input any url(I tried [this](https://youtu.be/kO6UrvK82pg?si=Xst7bg5kBZ3OHqRk) and [this](https://soundcloud.com/letiamash/bi-doromoyou-letiamash-bootleg-fc-anicommune-vol3)
4. Failed to import video/music data
```
Download failed. Url: https://soundcloud.com/letiamash/bi-doromoyou-letiamash-bootleg-fc-anicommune-vol3
com.yausername.youtubedl_android.YoutubeDLException: WARNING: ffmpeg-location /data/app/~~HQaWloV2J1jgE0yKCH51uQ==/net.turtton.ytalarm-F5COsz8ucuQ5LZfo6WOpZA==/lib/x86_64/libffmpeg.so does not exist! Continuing without ffmpeg
ERROR: [soundcloud] None: Unable to download JSON metadata: <urlopen error [Errno 7] No address associated with hostname> (caused by URLError(gaierror(7, 'No address associated with hostname')))
                                                                                                    
at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.kt:202)
at com.yausername.youtubedl_android.YoutubeDL.execute$default(YoutubeDL.kt:141)
at net.turtton.ytalarm.worker.VideoInfoDownloadWorker.download(VideoInfoDownloadWorker.kt:106)
at net.turtton.ytalarm.worker.VideoInfoDownloadWorker.doWork(VideoInfoDownloadWorker.kt:66)
at net.turtton.ytalarm.worker.VideoInfoDownloadWorker$doWork$1.invokeSuspend(Unknown Source:20)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

Related code:
https://github.com/turtton/YtAlarm/blob/af1e7e59b56a14bb35bbb925865518de78737c7d/app/src/main/kotlin/net/turtton/ytalarm/worker/VideoInfoDownloadWorker.kt#L106

**Expected behavior**
期待した挙動

Success import 

**Screenshots**
スクリーンショット(あれば)

![image](https://github.com/turtton/YtAlarm/assets/39013345/17162258-896b-4e41-b5ec-6ef8b813b728)

**Smartphone (please complete the following information):**
バグが発生した端末の情報
 - Device: Google Pixel5(Emulator
 - OS: Android 13(API 33)
 - Application Version(is it the latest version?) latest commit https://github.com/turtton/YtAlarm/commit/1b21e6d413b4d12f02e3ed57fc97fc937f1d7ee7

**Additional context**
その他追加で情報があればここに

**Comment by TechPro424** [comment]
Does this occur when trying to download from YT rather than soundcloud?

**Comment by turtton** [comment]
>  I tried yt and soundcloud but both failed.

**Comment by turtton** [comment]
It looks changed youtubedl-android behavior but I cannot find cause.
yt-dlp in command line looks not changed
```sh
┌─[turtton@tArchDesktop] - [~] - [日  2月 04, 19:33]
└─[$] <> URL=https://soundcloud.com/letiamash/bi-doromoyou-letiamash-bootleg-fc-anicommune-vol3                                                                                                             
┌─[turtton@tArchDesktop] - [~] - [日  2月 04, 19:33]
└─[$] <> yt-dlp --dump-single-json -f b $URL | jq '. | {id: .id, title: .fulltitle, type: ._type, thumbnailId: .thumbnail, url: .webpage_url, video_url: .url, domain: .webpage_url_domain}'
{
  "id": "1555258468",
  "title": "[Buy→FreeDL] ビードロ模様 (Letiamash Bootleg) [F/C AniCommune vol.3]",
  "type": "video",
  "thumbnailId": "https://i1.sndcdn.com/artworks-sk1NdKfzy5iLWECy-RUIfSg-original.jpg",
  "url": "https://soundcloud.com/letiamash/bi-doromoyou-letiamash-bootleg-fc-anicommune-vol3",
  "video_url": "https://cf-media.sndcdn.com/y5GWykGsLML5.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20veTVHV3lrR3NMTUw1LjEyOC5tcDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzA3MDQzMjExfX19XX0_&Signature=S9myuxdba5UBdDa6x1SwLj~w5aOAkWJm7JaDmOr0gwx0v32igvH7uqUmzJ0WpyYFUE80Mx1lordg2zJqv0w0jwvrYZLAeNZGJmS2BQl33pTQAzi6e~YzXvHixMA75TEcvt7E4Tx3jCssGSCbJzJ1t5yFeldNJkuY8PAmovB04NpOtMZYVNlAMqDJxJEnXRxUeTC1vM2Ui~wIntGF6CYjTSMdiC~BZXBfL0uLA1jEHf3vkK8U0bDHE11hn9zUQKjN5xOSEUujALxIp-9QKPVltflOV5jg0VcxFjwuVkuxO1BFLX5~qB77~w2s~9N6WBfwXf7nzdQTju-Wr4FkYA27qg__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ",
  "domain": "soundcloud.com"
}
```

**Comment by turtton** [comment]
I tested in physical device  GooglePixel6a(Android 14) and succeed importing YT and soundcloud, but failed to play YT video.
Emulator sometimes failed to resolve DNS....🤔

**Comment by TechPro424** [comment]
I created a library that's an abstraction for https://github.com/sealedtx/java-youtube-downloader and makes it extremely easy to download YT videos using Java
It's here: https://github.com/TechPro424/JavaYTDL

I've set up an action to publish it to GitHub Packages, and one package has been published, but I don't know how to let people use it
See https://github.com/TechPro424/JavaYTDL/packages/2064891?version=unspecified

**Comment by turtton** [comment]
MavenRegistry on Github is not recommended to use as it always requires authentication to import dependency.

YtAlarm uses [youtubedl-android](https://github.com/yausername/youtubedl-android) to support various websites and I have no plans to change to other libraries.

**Comment by TechPro424** [comment]
Then you could create an issue on their repo, and maybe temporarily use my library with https://jitpack.io/

**Comment by turtton** [comment]
I do not know why, but everything looks work fine for now, so close this issue.
